[package]
name = "feather-util"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
vek = "0.10"
nalgebra-glm = "0.6"
num-traits = "0.2"
num-derive = "0.3"
hash32 = "0.1"
hash32-derive = "0.1"
