[package]
name = "asynk-hyper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asynk = { path = "../asynk" }

hyper = { version = "1.2.0", features = ["server", "http1", "http2"] }
futures = "0.3.30"
http-body-util = "0.1.1"
