[package]
name = "test36_vst_tube"
version = "0.1.0"
authors = ["DevNul <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.2.0"


[lib]
name = "test36_vst_tube"
crate-type = ["cdylib"]