[package]
edition = "2018"
name = "rayon-demo"
version = "0.0.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
publish = false

[dependencies]
rayon = "1.3.0"
cgmath = "0.17"
docopt = "1"
fixedbitset = "0.2.0"
glium = "0.25.1"
lazy_static = "1"
odds = "0.3"
rand = "0.7"
rand_xorshift = "0.2"
regex = "1"
time = "0.1"

[dependencies.serde]
version = "1.0.85"
features = ["derive"]

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi"] }

[dev-dependencies]
num = "0.2"
