[package]
name = "macroses"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version = "1", features = ["full"]}
quote = "1"
proc-macro2 = "1"
proc-macro-error = "1"
trybuild = "1"

[lib]
proc-macro = true