[package]
name = "logger"
version = "0.1.0"
authors = ["Sebastian Waisbrot <seppo0010@gmail.com>"]

[target.x86_64-unknown-linux-gnu.dependencies]
syslog = "2.2.0"

[target.x86_64-apple-darwin.dependencies]
syslog = "2.2.0"
