[package]
name = "test71_google_cloud_storage"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

[dependencies]
eyre = "0.6"
color-eyre = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-error = "0.1"
tokio = {version = "1.11", features = ["full"]}
dotenv = "0.15"
hyper = {version = "0.14", features = ["http1", "http2", "client", "tcp", "stream", "runtime"]}
hyper-rustls = "0.22"
mime = "0.3"
http-body = "0.4"
futures = "0.3"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
base64 = "0.13"
urlencoding = "2.1"
chrono = "0.4"
rsa = "0.5"
sha2 = "0.9"
ring = "0.16"
rand = "0.8"

[dev-dependencies]