[package]
name = "test75_algorythm"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
eyre = "0.6"
color-eyre = "0.5"
bytesize = "1.1"
cuckoofilter = "0.5"
bloomfilter = "1.0"
rand = "0.8"
smallstr = "0.2"
hyperloglogplus = {version = "0.4", features = ["const-loop"]}
