# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "test56_rest"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

# TODO: только нужные значения опций
# TODO: rustls

[dependencies]
actix-web = "3.3.2"
actix-multipart = "0.3.0"
serde = "1.0.120"
serde_json = "1.0.61"
http = "0.2.3"
futures = "0.3.12"
# scopeguard = "1.1.0"
tokio = {version = "0.2.24", features = ["fs"]}
uuid = {version = "0.8.2", features = ["v4"]}

[dev-dependencies]
actix-rt = "1.1.1"
actix-multipart-rfc7578 = "0.2.1"
# multipart = "0.17.1"
# reqwest = {version = "0.11.0", features = ["multipart"]}