# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "test56_rest"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
serde = "1.0.120"
serde_json = "1.0.61"
http = "0.2.3"

[dev-dependencies]
actix-rt = "1.1.1"