blank_issues_enabled: false
contact_links:
  - name: Discourse forum for vaultwarden
    url: https://vaultwarden.discourse.group/
    about: Use this forum to request features or get help with usage/configuration.
  - name: GitHub Discussions for vaultwarden
    url: https://github.com/dani-garcia/vaultwarden/discussions
    about: An alternative to the Discourse forum, if this is easier for you.
