[package]
name = "feather-server-config"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-util = { path = "../../core/util" }

tokio = { version = "0.2", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
humantime-serde = "1.0"
toml = "0.5"
