[package]
name = "test95_bincode"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2021"

##############################################################################################################

[dependencies]
serde = {version = "^1.0.197", features = ["derive"]}
serde_json = "^1.0.114"
bincode = "^1.3.3"