name: Release
on:
  push:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build on Windows"
      run: cargo build --target x86_64-pc-windows-gnu
