[package]
name = "test93_vtable"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2021"

##############################################################################################################

[dependencies]
