[package]
name = "feather-server-util"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-core = { path = "../../core" }
feather-server-types = { path = "../types" }

fecs = { git = "https://github.com/feather-rs/fecs", rev = "0c4838d65b41ca059012b6e9147eabf0c275a731" }
nalgebra-glm = "0.6"
arrayvec = "0.5"
smallvec = "1.4"
rand = "0.7"
rand_distr = "0.2"
itertools = "0.9"
ahash = "0.3"
inventory = "0.1"
anyhow = "1.0"
uuid = { version = "0.8", features = ["v3"] }
md5 = "0.7"
reqwest = { version = "^0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
