# https://github.com/eqrion/cbindgen/blob/master/template.toml
# https://github.com/eqrion/cbindgen/blob/master/docs.md

language = "C" # "C++" / "C"
include_version = true
namespace = ""  # Пространство имен библиотеки, "rust_lib"
namespaces = []         # Пространство имен библиотеки
using_namespaces = []
sys_includes = [] # Какие инклюды в <> должны быть в библиотеке в .h ("cstdio", "cstring")
includes = []   # Какие инклюды в "" должны быть в библиотеке в .h
no_includes = false
braces = "SameLine"
line_length = 100
tab_width = 4
documentation_style = "auto"
style = "both"
header = ""
autogen_warning = """
struct PairOperands;
struct ExpressionFfi;
struct ExpressionFfi;
"""
include_guard = "RUST_LIBRARY"
# trailer = "/* Text to put at the end of the generated file */"


[defines]
# "target_os = freebsd" = "DEFINE_FREEBSD"
# "feature = serde" = "DEFINE_SERDE"

[export]
include = []
exclude = []
item_types = []
renaming_overrides_prefixing = false
# prefix = "RUST_" # Префикс у всех структур

[export.rename]

# [export.pre_body]

[export.body]

[fn]
prefix = 'extern "C"' # Если выставлен язык C - тогда мы добавляем префикс
# args = "auto"
# rename_args = "CamelCase" # переименование полей в camelCase
# must_use = "RUST"
# postfix = "END_FUNC"

[struct]
derive_constructor = false   # Конструктор у структур
derive_eq = false            # EQ у структур
derive_neq = false
derive_lt = false
derive_lte = false
derive_gt = false
derive_gte = false
# rename_fields = "CamelCase"
# must_use = "MUST_USE_STRUCT"

[enum]
rename_variants = "None"
add_sentinel = false
prefix_with_name = false
derive_helper_methods = false
derive_const_casts = false
derive_mut_casts = false
derive_tagged_enum_destructor = false
derive_tagged_enum_copy_constructor = false
enum_class = false
private_default_tagged_enum_constructor = false
# cast_assert_name = "ASSERT"
# must_use = "MUST_USE_ENUM"

[const]
allow_static_const = true

[macro_expansion]
bitflags = false

[parse]
parse_deps = true
exclude = []
clean = false
extra_bindings = []
# include = []

[parse.expand]
crates = []
all_features = false
default_features = true
features = []
