TEST_APP:
	$(shell rm -rf "/Users/devnul/projects/island2/project/res_result")
	export RUST_LOG=info && \
	cargo run --release -- \
		--input_folder "/Users/devnul/projects/island2/project/res" \
		--output_folder "/Users/devnul/projects/island2/project/res_result" \
		--target_quality 25