[package]
name = "test67_nom"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
color-eyre = "0.6"
nom = "7"
log = "0.4"
env_logger = "0.9"

[profile.release]
# lto = true
# codegen-units = 1
# panic = "abort"