[package]
name = "pkcs7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hash-function-wrapper = { version = "0.1.0", path = "../hash-function-wrapper" }
serde = {version = "1.0.201", features = ["derive"]}
serde_json = "1.0.117"
