[package]
name = "feather-server-commands"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-core = { path = "../../core" }
feather-server-types = { path = "../types" }
feather-server-util = { path = "../util" }
feather-definitions = { path = "../../definitions" }

fecs = { git = "https://github.com/feather-rs/fecs", rev = "0c4838d65b41ca059012b6e9147eabf0c275a731" }
lieutenant = { git = "https://github.com/feather-rs/lieutenant", branch = "master" }
smallvec = "1.4"
anyhow = "1.0"
thiserror = "1.0"
rand = "0.7"
vek = "0.10"
uuid = { version = "0.8", features = ["v3"] }
tokio = { version = "0.2", features = ["full"] }
