[package]
name = "test70_aws_s3_rest_api"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

[dependencies]
eyre = "0.6"
color-eyre = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-error = "0.1"
tokio = {version = "1.11", features = ["full"]}
dotenv = "0.15"
hyper = {version = "0.14", features = ["http1", "http2", "client", "tcp", "stream", "runtime"]}
# hyper-tls = "0.5"
hyper-rustls = "0.22"
mime = "0.3"
http-body = "0.4"
futures = "0.3"
chrono = "0.4"
sha2 = "0.9"
# hmac = "0.11"
hmac-sha256 = "0.1.7"
hex = "0.4"

[dev-dependencies]