[target.arm-unknown-linux-gnueabi]
image = "devnul/armv6_openssl"

# [build.env]

[target.arm-unknown-linux-gnueabi.env]
passthrough = [
    "OPENSSL_DIR",
    "TARGET",
    "MACHINE",
    "ARCH",
    "CC"
]