[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = {version = "0.8.5"}
hand-made-math = {path = "../../hand-made-math"}
num-bigint = "0.4.5"
num-traits = "0.2.19"
num-primes = "0.3.0"
