[package]
name = "feather-server-player"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-core = { path = "../../core" }
feather-definitions = { path = "../../definitions" }
feather-server-types = { path = "../types" }
feather-server-util = { path = "../util" }
feather-server-network = { path = "../network" }
feather-server-commands = { path = "../commands" }
entity = { path = "../entity", package = "feather-server-entity" }

fecs = { git = "https://github.com/feather-rs/fecs", rev = "0c4838d65b41ca059012b6e9147eabf0c275a731" }
log = "0.4"
mojang-api = "0.6"
once_cell = "1.4.0"
nalgebra-glm = "0.6"
smallvec = "1.4"
itertools = "0.9"
ahash = "0.3"
parking_lot = "0.10"
thiserror = "1.0"
anyhow = "1.0"
inventory = "0.1"
