name: coverage
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  GITHUB_BOT_CONTEXT_STRING: "coveralls coverage reporting job"

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "v2"

      - name: Install gnome-keyring and keyutils on Linux
        run: |
          sudo apt-get update --yes && sudo apt-get install --yes gnome-keyring keyutils
          rm -f $HOME/.local/share/keyrings/*
          echo -n "test" | gnome-keyring-daemon --unlock

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Build
        run: source <(cargo llvm-cov show-env --export-prefix) && cargo build

      - name: Test
        run: source <(cargo llvm-cov show-env --export-prefix) && cargo test

      - name: Generate code coverage
        run: source <(cargo llvm-cov show-env --export-prefix) && cargo llvm-cov report --lcov --output-path coverage.lcov --ignore-filename-regex '(bench\/|integration\/|tools\/|tpc\/)'

      - name: Upload code to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  finalize_coverage:
    runs-on: ubuntu-latest
    needs: coverage
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Everything is fine
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Something went wrong
        if: ${{ contains(needs.*.result, 'failure') && github.event_name == 'push' }}
        uses: JasonEtco/create-an-issue@v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BOT_CONTEXT_STRING: "coveralls coverage reporting job"
        with:
          filename: .github/BOT_ISSUE_TEMPLATE.md
