[package]
name = "test60_diesel"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = {version = "1.4.6", features = ["postgres"]}
dotenv = "0.15.0"
# diesel_migrations = {version = "1.4.0", features = ["postgres"]}