[package]
name = "feather-blocks-generator"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[lib]
name = "feather_blocks_generator"
path = "src/lib.rs"

[[bin]]
name = "feather-blocks-generator"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
indexmap = { version = "1", features = ["serde-1"] }
quote = "1"
syn = "1"
proc-macro2 = "1"
heck = "0.3"
once_cell = "1"
maplit = "1"
bincode = "1"
