# A records

[[cmd]]
name = "Look up an existing A record using TCP"
shell = "dog a-example.lookup.dog @1.1.1.1 --short --tcp"
stdout = { string = '10.20.30.40' }
stderr = { empty = true }
status = 0
tags = [ "live", "cloudflare", "tcp", "a" ]

[[cmd]]
name = "Look up a missing A record using TCP"
shell = "dog non.existent @1.1.1.1 --short --tcp"
stdout = { empty = true }
stderr = { string = "No results" }
status = 2
tags = [ "live", "cloudflare", "tcp", "a" ]


# AAAA records

[[cmd]]
name = "Look up an existing AAAA record using TCP"
shell = "dog AAAA aaaa-example.lookup.dog @1.1.1.1 --short --tcp"
stdout = { string = '::1' }
stderr = { empty = true }
status = 0
tags = [ "live", "cloudflare", "tcp", "aaaa" ]

[[cmd]]
name = "Look up a missing AAAA record using TCP"
shell = "dog AAAA non.existent @1.1.1.1 --short --tcp"
stdout = { empty = true }
stderr = { string = "No results" }
status = 2
tags = [ "live", "cloudflare", "tcp", "aaaa" ]


# CAA records

[[cmd]]
name = "Look up an existing CAA record using TCP"
shell = "dog CAA caa-example.lookup.dog @1.1.1.1 --short --tcp"
stdout = { string = '"issue" "some.certificate.authority" (non-critical)' }
stderr = { empty = true }
status = 0
tags = [ "live", "cloudflare", "tcp", "caa" ]

[[cmd]]
name = "Look up a missing CAA record using TCP"
shell = "dog CAA non.existent @1.1.1.1 --short --tcp"
stdout = { empty = true }
stderr = { string = "No results" }
status = 2
tags = [ "live", "cloudflare", "tcp", "caa" ]


# CNAME records

[[cmd]]
name = "Look up an existing CNAME record using TCP"
shell = "dog CNAME cname-example.lookup.dog @1.1.1.1 --short --tcp"
stdout = { string = '"dns.lookup.dog."' }
stderr = { empty = true }
status = 0
tags = [ "live", "cloudflare", "tcp", "cname" ]

[[cmd]]
name = "Look up a missing CNAME record using TCP"
shell = "dog CNAME non.existent @1.1.1.1 --short --tcp"
stdout = { empty = true }
stderr = { string = "No results" }
status = 2
tags = [ "live", "cloudflare", "tcp", "cname" ]


# HINFO records

[[cmd]]
name = "Look up an existing HINFO record using TCP"
shell = "dog HINFO hinfo-example.lookup.dog @1.1.1.1 --short --tcp"
stdout = { string = '"some-kinda-cpu"' }
stderr = { empty = true }
status = 0
tags = [ "live", "cloudflare", "tcp", "hinfo" ]

[[cmd]]
name = "Look up a missing HINFO record using TCP"
shell = "dog HINFO non.existent @1.1.1.1 --short --tcp"
stdout = { empty = true }
stderr = { string = "No results" }
status = 2
tags = [ "live", "cloudflare", "tcp", "hinfo" ]


# MX records

[[cmd]]
name = "Look up an existing MX record using TCP"
shell = "dog MX mx-example.lookup.dog @1.1.1.1 --short --tcp"
stdout = { string = '10 "some.mail.server."' }
stderr = { empty = true }
status = 0
tags = [ "live", "cloudflare", "tcp", "mx" ]

[[cmd]]
name = "Look up a missing MX record using TCP"
shell = "dog MX non.existent @1.1.1.1 --short --tcp"
stdout = { empty = true }
stderr = { string = "No results" }
status = 2
tags = [ "live", "cloudflare", "tcp", "mx" ]


# NS records

[[cmd]]
name = "Look up an existing NS record using TCP"
shell = "dog NS lookup.dog @1.1.1.1 --short --tcp"
stdout = { string = 'ns1' }
stderr = { empty = true }
status = 0
tags = [ "live", "cloudflare", "tcp", "ns" ]

[[cmd]]
name = "Look up a missing NS record using TCP"
shell = "dog NS non.existent @1.1.1.1 --short --tcp"
stdout = { empty = true }
stderr = { string = "No results" }
status = 2
tags = [ "live", "cloudflare", "tcp", "ns" ]


# SOA records

[[cmd]]
name = "Look up an existing SOA record using TCP"
shell = "dog SOA lookup.dog @1.1.1.1 --short --tcp"
stdout = { string = 'ns1' }
stderr = { empty = true }
status = 0
tags = [ "live", "cloudflare", "tcp", "soa" ]

[[cmd]]
name = "Look up a missing SOA record using TCP"
shell = "dog MX non.existent @1.1.1.1 --short --tcp"
stdout = { empty = true }
stderr = { string = "No results" }
status = 2
tags = [ "live", "cloudflare", "tcp", "soa" ]


# SRV records

[[cmd]]
name = "Look up an existing SRV record using TCP"
shell = "dog SRV srv-example.lookup.dog @1.1.1.1 --short --tcp"
stdout = { string = '20 "dns.lookup.dog.":5000' }
stderr = { empty = true }
status = 0
tags = [ "live", "cloudflare", "tcp", "srv" ]

[[cmd]]
name = "Look up a missing SRV record using TCP"
shell = "dog SRV non.existent @1.1.1.1 --short --tcp"
stdout = { empty = true }
stderr = { string = "No results" }
status = 2
tags = [ "live", "cloudflare", "tcp", "srv" ]


# TXT records

[[cmd]]
name = "Look up an existing TXT record using TCP"
shell = "dog TXT txt-example.lookup.dog @1.1.1.1 --short --tcp"
stdout = { string = '"Cache Invalidation and Naming Things"' }
stderr = { empty = true }
status = 0
tags = [ "live", "cloudflare", "tcp", "txt" ]

[[cmd]]
name = "Look up a missing TXT record using TCP"
shell = "dog TXT non.existent @1.1.1.1 --short --tcp"
stdout = { empty = true }
stderr = { string = "No results" }
status = 2
tags = [ "live", "cloudflare", "tcp", "txt" ]
