[package]
name = "qwatro-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.67"
futures = "0.3.27"
log = "0.4.17"
tokio = { version = "1.26.0", features = ["net", "io-util", "time", "macros", "rt-multi-thread"] }
tokio-util = "0.7.7"
