# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

################################################################################

[package]
name = "ipc"
version = "0.1.0"
edition = "2021"

################################################################################

[dependencies]
clap = { version = "^4.4.11", features = ["derive"] }
shared_memory = "^0.12.4"
humantime = "^2.1.0"
portpicker = "^0.1.1"
raw_sync = "^0.1.5"
iceoryx2 = "^0.4.1"
memmap2 = "^0.9.4"
os_pipe = "^1.2.1"
rand = "^0.8.5"
core_affinity = "=0.6.1"

################################################################################

[dev-dependencies]
divan = "^0.1.14"

################################################################################

[lib]

################################################################################

# [[bench]]
# name = "examples"
# harness = false
