[package]
name = "throttled-stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
pin-project-lite = "0.2.9"
tokio = { version = "1.27.0", features = ["full"] }
