[package]
name = "test68_aws_lambda"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
# eyre = "0.6"
# color-eyre = "0.5"
log = "0.4"
env_logger = "0.9"
lambda_runtime = "0.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = "1.10"

[profile.release]
# lto = true
# codegen-units = 1
# panic = "abort"