[package]
name = "test86_thirtyfour"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thirtyfour = "^0.31"
tokio = {version = "^1", default-features = false, features = ["full"]}
url = "^2"

# Serde
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"