[[cmd]]
name = "Running dog with ‘--wibble’ warns about the invalid argument"
shell = "dog --wibble"
stdout = { empty = true }
stderr = { file = "outputs/invalid-argument.txt" }
status = 3
tags = [ 'options' ]

[[cmd]]
name = "Running dog with ‘--class’ warns about the missing argument parameter"
shell = "dog --class"
stdout = { empty = true }
stderr = { file = "outputs/missing-parameter.txt" }
status = 3
tags = [ 'options' ]

[[cmd]]
name = "Running dog with ‘--type XYZZY’ warns about the invalid record type"
shell = "dog --type XYZZY dns.google"
stdout = { empty = true }
stderr = { file = "outputs/invalid-query-type.txt" }
status = 3
tags = [ 'options' ]

[[cmd]]
name = "Running dog with ‘--class XYZZY’ warns about the invalid class"
shell = "dog --class XYZZY dns.google"
stdout = { empty = true }
stderr = { file = "outputs/invalid-query-class.txt" }
status = 3
tags = [ 'options' ]

[[cmd]]
name = "Running dog with ‘-Z aoeu’ warns about the invalid protocol tweak"
shell = "dog -Z aoeu dns.google"
stdout = { empty = true }
stderr = { file = "outputs/invalid-protocol-tweak.txt" }
status = 3
tags = [ 'options' ]

[[cmd]]
name = "Running dog with ‘OPT’ warns that OPT requests are sent by default"
shell = "dog OPT dns.google"
stdout = { empty = true }
stderr = { file = "outputs/opt-query.txt" }
status = 3
tags = [ 'options' ]

[[cmd]]
name = "Running dog with ‘opt’ also warns that OPT requests are sent by default"
shell = "dog opt dns.google"
stdout = { empty = true }
stderr = { file = "outputs/opt-query.txt" }
status = 3
tags = [ 'options' ]

[[cmd]]
name = "Running dog with ‘--type OPT’ warns that OPT requests are sent by default"
shell = "dog --type OPT dns.google"
stdout = { empty = true }
stderr = { file = "outputs/opt-query.txt" }
status = 3
tags = [ 'options' ]

[[cmd]]
name = "Running dog with ‘--type opt’ also warns that OPT requests are sent by default"
shell = "dog --type opt dns.google"
stdout = { empty = true }
stderr = { file = "outputs/opt-query.txt" }
status = 3
tags = [ 'options' ]

[[cmd]]
name = "Running dog with a domain longer than 255 bytes warns about it being too long"
shell = "dog 12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
stdout = { empty = true }
stderr = { file = "outputs/huge-domain.txt" }
status = 3
tags = [ 'options' ]

[[cmd]]
name = "Running dog with ‘--https’ and no nameserver warns that one is missing"
shell = "dog --https dns.google"
stdout = { empty = true }
stderr = { file = "outputs/missing-nameserver.txt" }
status = 3
tags = [ 'options' ]
