# help

[[cmd]]
name = "Running ‘dog --help’ shows help"
shell = "dog --help"
stdout = { string = "dog ●" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]

[[cmd]]
name = "Running ‘dog --help --color=automatic’ not to a terminal shows help without colour"
shell = "dog --help --color=automatic"
stdout = { string = "dog ●" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]

[[cmd]]
name = "Running ‘dog --help --colour=always’ shows help with colour"
shell = "dog --help --colour=always"
stdout = { string = "dog \u001B[1;32m●\u001B[0m" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]

[[cmd]]
name = "Running ‘dog --help --color=never’ shows without colour"
shell = "dog --help --color=never"
stdout = { string = "dog ●" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]

[[cmd]]
name = "Running ‘dog’ with no arguments shows help"
shell = "dog"
stdout = { string = "dog ●" }
stderr = { empty = true }
status = 3
tags = [ 'options' ]


# versions

[[cmd]]
name = "Running ‘dog --version’ shows version information"
shell = "dog --version"
stdout = { string = "dog ●" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]

[[cmd]]
name = "Running ‘dog --version --colour=automatic’ not to a terminal shows version information without colour"
shell = "dog --version --colour=automatic"
stdout = { string = "dog ●" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]

[[cmd]]
name = "Running ‘dog --version --color=always’ shows version information with colour"
shell = "dog --version --color=always"
stdout = { string = "dog \u001B[1;32m●\u001B[0m" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]

[[cmd]]
name = "Running ‘dog --version --colour=never’ shows version information without colour"
shell = "dog --version --colour=never"
stdout = { string = "dog ●" }
stderr = { empty = true }
status = 0
tags = [ 'options' ]
