[package]
name = "test12_cargo"
version = "0.1.0"
authors = ["Pavel Ershov <pershov@game-insight.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
library_1 = { path = "libs/library_1" }
library_2 = { path = "libs/library_2" }

[workspace]
