[package]
name = "test59_auth_server"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
actix-http = "2.2.0"
actix-service = "1.0.6"
actix-files = "0.5.0"
actix-web-httpauth = "0.5.1"
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
tracing-appender = "0.1.2"
tracing-futures = "0.2.5"
tracing-actix-web = "0.2.1"
futures = "0.3.13"
serde = "1.0.125"
serde_json = "1.0.64"
serde_with = "1.7.0"
quick-error = "2.0.0"
url = "2.2.1"
jsonwebtoken = "7.2.0"      # Парсинг токенов
rust-argon2 = "0.8.3"       # Хеширование паролей
rand = "0.8.3"
validator = {version = "0.13.0", features = ["derive"]}
uuid = { version = "0.8.2", features = ["v4", "serde"] }
chrono = {version = "0.4.19", features = [ "serde" ] }

[dependencies.sqlx]
version = "0.4.2"
features = ["postgres", "runtime-actix-rustls", "macros", "migrate", "uuid", "chrono", "offline"]
# default-features = false

[dev-dependencies]
http-auth-basic = "0.1.2"