language: rust
sudo: false
rust: stable

addons:
  apt:
    packages:
      - tcl8.5

before_script:
  - cargo build

script:
  - tclsh8.5 tests/test_helper.tcl
  - cargo test --verbose --package command
  - cargo test --verbose --package compat
  - cargo test --verbose --package config
  - cargo test --verbose --package database
  - cargo test --verbose --package logger
  - cargo test --verbose --package networking
  - cargo test --verbose --package parser
  - cargo test --verbose --package response
  - cargo test --verbose --package rdbutil
  - cargo test --verbose --package util

notifications:
  email: false
