[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
num-primes = {version = "0.3.0"}
num-bigint = {version = "0.4.5", features = ["rand"]}
rand = "0.8.5"
hand-made-sha = {path = "../../hand-made-sha"}
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
