on:
  push:
    branches:
      - '**'
      - '!master'

name: cargo-deny

jobs:
  deny-check:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
