[package]
name = "plugin-message"
version = "0.1.0"
authors = ["Derek Lee <derek.scott.lee13@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
quill = { path = "../../api" }
