[package]
name = "feather-server"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"
default-run = "feather-server"

[lib]
name = "feather_server"
path = "src/lib.rs"

[[bin]]
name = "feather-server"
path = "src/main.rs"

[dependencies]
# Feather crates
feather-core = { path = "../core" }
feather-server-block = { path = "block" }
feather-server-chat = { path = "chat" }
feather-server-chunk = { path = "chunk" }
feather-server-config = { path = "config" }
feather-server-entity = { path = "entity" }
feather-server-lighting = { path = "lighting" }
feather-server-network = { path = "network" }
feather-server-packet-buffer = { path = "packet_buffer" }
feather-server-physics = { path = "physics" }
feather-server-player = { path = "player" }
feather-server-types = { path = "types" }
feather-server-util = { path = "util" }
feather-server-weather = { path = "weather" }
feather-server-worldgen = { path = "worldgen" }

fecs = { git = "https://github.com/feather-rs/fecs", rev = "0c4838d65b41ca059012b6e9147eabf0c275a731" }
tokio = { version = "0.2", features = ["full"] }
simple_logger = "1.6"
log = "0.4"
anyhow = "1.0"
rand = "0.7"
fxhash = "0.2"
base64 = "0.12"
spin_sleep = "1.0"
crossbeam = "0.7"
ctrlc = "3.1"
