name: Regenerate and upload CycloneDX Manifest on changes to Cargo.lock files

on:
  push:
    paths:
      - Cargo.lock
      - src/bin/shim-kvm/Cargo.lock
      - src/bin/shim-sgx/Cargo.lock
      - src/bin/exec-wasmtime/Cargo.lock

jobs:
  Regenerate-BOM:
    uses: ./.github/workflows/sbom_manifest_action.yml

