[profile.release]
lto = true
codegen-units = 1

[workspace]
resolver = "2"
members = ["bench", "cli", "examples", "integration", "sdk", "server", "tools"]

[workspace.metadata.cargo-machete]
ignored = ["openssl"]
