[package]
name = "quill-common"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1"
bytemuck = { version = "1", features = ["derive"] }
derive_more = "0.99.16"
libcraft-core = { path = "../../libcraft/core" }
libcraft-particles = { path = "../../libcraft/particles" }
libcraft-text = { path = "../../libcraft/text" }
serde = { version = "1", features = ["derive"] }
smartstring = { version = "0.2", features = ["serde"] }
uuid = { version = "0.8", features = ["serde"] }

[dev-dependencies]
quill = { path = "../api" }
