[package]
name = "test58_oauth"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
handlebars = "3.5.3"
actix-files = "0.5.0"
serde = "1.0.125"
serde_json = "1.0.64"
quick-error = "2.0.0"