[package]
name = "test58_oauth"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
actix-http = "2.2.0"
actix-identity = "0.3.1"
actix-files = "0.5.0"
actix-service = "1.0.6"
futures = "0.3.13"
serde = "1.0.125"
serde_json = "1.0.64"
handlebars = "3.5.3"
quick-error = "2.0.0"
rand = "0.8.3"
log = "0.4.14"
env_logger = "0.8.3"
url = "2.2.1"