[package]
name = "hand-made-group-digital-signature"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hand-made-math = { version = "0.1.0", path = "../hand-made-math" }
hand-made-sha = { version = "0.1.0", path = "../hand-made-sha" }
hand-made-streebog = { version = "0.1.0", path = "../hand-made-streebog" }
num = { version = "0.4.3", features = ["rand", "num-bigint"] }
num-bigint = { version = "0.4.6", features = ["rand"] }
num-primes = "0.3.0"
primal = "0.3.2"
rand = "0.8.5"
