[package]
name = "feather-server"
version = "0.1.0"
authors = [ "caelunshun <caelunshun@gmail.com>" ]
edition = "2018"
default-run = "feather-server"

[[bin]]
path = "src/main.rs"
name = "feather-server"

[lib]
path = "src/lib.rs"

[dependencies]
ahash = "0.7"
anyhow = "1"
base = { path = "../base", package = "feather-base" }
base64 = "0.13"
time = { version = "0.3", features = ["local-offset", "formatting", "macros"] }
colored = "2"
common = { path = "../common", package = "feather-common" }
crossbeam-utils = "0.8"
ecs = { path = "../ecs", package = "feather-ecs" }
fern = "0.6"
flate2 = "1"
flume = "0.10"
futures-lite = "1"
hematite-nbt = { git = "https://github.com/PistonDevelopers/hematite_nbt" }
log = "0.4"
md-5 = "0.9"
num-bigint = "0.4"
num-traits = "0.2"
once_cell = "1"
parking_lot = "0.11"
plugin-host = { path = "../plugin-host", package = "feather-plugin-host" }
protocol = { path = "../protocol", package = "feather-protocol" }
quill-common = { path = "../../quill/common" }

rand = "0.8"
ring = "0.16"

rsa = "0.5"
rsa-der = "0.3"
base64ct = "1"

serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
sha-1 = "0.9"
tokio = { version = "1", features = [ "full" ] }
toml = "0.5"
ureq = { version = "2", features = [ "json" ] }
utils = { path = "../utils", package = "feather-utils" }
uuid = "0.8"
slab = "0.4"
libcraft-core = { path = "../../libcraft/core" }
libcraft-items = { path = "../../libcraft/items" }
worldgen = { path = "../worldgen", package = "feather-worldgen" }

[features]
default = [ "plugin-cranelift" ]

# Use zlib-ng for faster compression. Requires CMake.
zlib-ng = [ "flate2/zlib-ng-compat" ]

# Use Cranelift to JIT-compile plugins. Pure Rust
# but produces slower code than LLVM.
plugin-cranelift = [ "plugin-host/cranelift" ]
# Use LLVM to JIT-compile plugins. Produces
# very fast code, but requires LLVM to be installed
# on the build system. May impact startup times.
plugin-llvm = [ "plugin-host/llvm" ]
