# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "currency_lib",
    "currencies_request_cli",
    "telegram_bot"
]
default-members = [
    "telegram_bot", 
    "currencies_request_cli"
]