[package]
name = "server"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
color-eyre = "0.5"
log = "0.4"
pretty_env_logger = "0.4"
tokio = {version = "1.14", features = ["full"]}
rcgen = "0.8"
rustls = "0.20"
quinn = "0.8"
futures = "0.3"