[package]
name = "cblt"
version = "0.1.9"
edition = "2021"

authors = ["Evgeny Igumnov <igumnovnsk@gmail.com>"]

repository = "https://github.com/evgenyigumnov/cblt"
license = "MIT"
description = "Safe and fast minimalistic web server, written in Rust, that serves files from a directory and proxies requests to another server."
keywords = ["web-server", "http", "proxy", "reverse-proxy", "file-server"]
categories = ["web-programming", "network-programming", "development-tools"]

exclude = ["benchmark", "assets"]


[[bin]]
name = "cblt"
path = "src/main.rs"


[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
http = "1.1.0"
env_logger = "0.11.5"
log = "0.4.22"
kdl = "4.6.0"
reqwest = { version = "0.12.9", features = ["stream"] }
bytes = "1.8.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
httparse = "1.9.5"
itoa = "1.0.11"
rustls = { version = "0.23.16"}
tokio-rustls = "0.26.0"
clap = { version = "4.5.20", features = ["derive"] }
futures-core = "0.3.31"
futures-util = "0.3.31"
async-compression = { version = "0.4.17", features = ["tokio", "gzip"] }
thiserror = "2.0.3"
anyhow = "1.0.93"

[profile.release]
lto = true