[package]
name = "hw8-fifteen"
version = "0.1.4"
edition = "2024"

[dependencies]
pathfinding = "4.14"
rand = "0.9"
slint = "1.13"
lazy_static = "1.5"
peak_alloc = "0.3"

[build-dependencies]
slint-build = "1.13"
