[package]
name = "bench"
version = "0.1.1"
edition = "2021"

[dependencies]
async-trait = "0.1.82"
clap = { version = "4.5.17", features = ["derive"] }
colored = "2.0.4"
derive_more = "1.0.0"
figlet-rs = "0.1.5"
futures = "0.3.30"
human_format = "1.1.0"
iggy = { path = "../sdk" }
integration = { path = "../integration" }
nonzero_lit = "0.1.2"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.14"
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.18", features = ["fmt", "env-filter"] }

[[bin]]
name = "iggy-bench"
path = "src/main.rs"
