[package]
name = "client"
description = ""
authors = []
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"

###########################################################################

[dependencies]
