[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = {version = "0.4.5", features = ["rand"]}
rand = "0.8.5"
client = {path = "../client"}
serde_json = "1.0.117"
hand-made-sha = {path = "../../hand-made-sha"}
