[package]
name = "test65_dynamodb"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

[dependencies]
backtrace = "0.3"
human-panic = "1.0"
sled = "0.34"

[dev-dependencies]