[package]
name = "libp2p_test"
description = ""
authors = []
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

###########################################################################

[dependencies]
libp2p = { version = "^0.54.1", default-features = false, features = [
    "dns",
    "noise",
    "tokio",
    "tcp",
    "itentify",
] }
tokio = { version = "^1.42.0", default-features = false, features = [
    "macros",
    "net",
] }
serde = { version = "^1.0.217", default-features = false, features = [
    "derive",
] }
serde_json = { version = "^1.0.134", default-features = false, features = [
    "derive",
] }
async-trait = "^0.1.83"
