[package]
name = "libp2p_research"
description = ""
authors = []
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

###########################################################################

[dependencies]
# Common
thiserror = { version = "^2.0.9", default-features = false, features = [] }

# Async
tokio = { version = "^1.42.0", default-features = false, features = [
    # "macros",
    "net",
] }
futures = { version = "^0.3.31", default-features = false, features = [] }
async-trait = { version = "^0.1.83", default-features = false, features = [] }

# Serde
serde = { version = "^1.0.217", default-features = false, features = [
    "derive",
] }
bincode = { version = "^1.3.3", default-features = false, features = [] }

# LibP2P
libp2p = { version = "^0.54.1", default-features = false, features = [
    "dns",
    "noise",
    "tokio",
    "tcp",
    "identify",
    "request-response",
] }

# serde_json = { version = "^1.0.134", default-features = false, features = [
#     "std",
# ] }
