language: rust

sudo: false

cache:
  directories:
    - $HOME/.cargo
    - $HOME/artifacts

before_install:
  - mkdir -p "$HOME/artifacts"
  - cd $TRAVIS_BUILD_DIR
  - export ARTIFACT_CACHE="$HOME/artifacts/$(rustc --version | sed 's/^rustc \([^ ]*\).*$/\1/g')"
  - mkdir -p "$ARTIFACT_CACHE"
  - rm -rf target
  - ln -s "$ARTIFACT_CACHE" target

rust:
  - stable
  - beta
  - nightly

script:
  - rustc --version
  - cargo build
  - cargo test --all

