[build-system]
build-backend = "maturin"
requires = ["maturin>=1.0,<2.0"]

[project]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
description = "Apache OpenDAL™ Python Binding"
license = { text = "Apache-2.0" }
name = "tcptest"

[tool.maturin]
features = ["pyo3/extension-module"]
