
TEST_JENKINS:
	cargo test -- jenkins::tests

TEST_SLACK:
	# cargo test --package slack_command_handler --bin slack_command_handler -- slack::tests::test_slack_client --exact --nocapture
	cargo test -- slack::tests