# Говорим карго, что нужно перекомпилировать core библиотеку

[build]
target = "x86_64-build_config.json"     # Файлик конфигурации билда

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]