[package]
name = "test85_allocation_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "^0.4"
smallstr = "^0.3"
# rand = "^0.8"

[[bench]]
name = "alloc_bench"
harness = false