[package]
name = "wasi-cap-std-sync"
version = "0.37.0"
authors = ["The Wasmtime Project Developers"]
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2021"
include = ["src/**/*", "README.md", "LICENSE" ]

[dependencies]
wasi-common = { path = "../", version = "=0.37.0" }
async-trait = "0.1"
anyhow = "1.0"
cap-std = "0.24.1"
cap-fs-ext = "0.24.1"
cap-time-ext = "0.24.1"
cap-rand = "0.24.1"
fs-set-times = "0.15.0"
system-interface = { version = "0.20.0", features = ["cap_std_impls"] }
tracing = "0.1.19"
io-lifetimes = { version = "0.5.0", default-features = false }
is-terminal = "0.1.0"

[target.'cfg(unix)'.dependencies]
rustix = "0.33.5"

[target.'cfg(windows)'.dependencies]
winapi = "0.3"
lazy_static = "1.4"
io-extras = "0.13.0"

[dev-dependencies]
tempfile = "3.1.0"
