[package]
name = "feather-misc"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-blocks = { path = "../blocks" }
feather-items = { path = "../items" }
ordinalizer = "0.1"
