[package]
name = "concurrent-map"
authors = ["Tyler Neely <tylerneely@gmail.com>"]
description = "a lock-free linearizable B+ tree"
version = "5.0.4"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/komora-io/concurrent-map"
keywords = ["lock-free", "multi-threaded", "performance", "index", "tree"]
categories = ["concurrency", "data-structures", "rust-patterns"]
readme = "README.md"

[profile.release]
debug = true

[features]
timing = []
fuzz_constants = []

[dependencies]
ebr = "0.2"
pagetable = "0.3"
