[package]
name = "test63_rabbitmq"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
tokio-amqp = "1.0.0"
lapin = { version = "1.7.0", features = [] }

[dev-dependencies]