[package]
name = "test63_rabbitmq"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "~1.5.0", features = ["full"] }
tokio-amqp = "~1.0.0"
lapin = { version = "~1.7.0", features = [] }
tracing = "~0.1.26"
tracing-subscriber = "~0.2.18"
tracing-futures = "~0.2.5"
human-panic = "~1.0.0"
quick-error = "~2.0.0"
dotenv = "~0.15.0"
futures = "~0.3.14"
tap = "~1.0.1"

[dev-dependencies]