# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "test54_sqlx"
version = "0.1.0"
authors = ["Pavel Ershov <pershov@game-insight.com>"]
edition = "2018"

[dependencies]
sqlx = {version="0.4.2", default-features = false, features=["runtime-tokio-rustls", "sqlite", "macros", "json"]}
tokio = "0.2.24"
futures = "0.3.8"

[build-dependencies]
