[package]
name = "test43_amethyst"
version = "0.1.0"
authors = [""]
edition = "2018"

[workspace]

[dependencies]
amethyst = { version="0.15.0", features = ["metal"] }
nalgebra = "0.19.0"
nalgebra-glm = "0.5.0"