---
devices:
  samplerate: 48000
  chunksize: 1024
  target_level: 1024
  adjust_period: 3
  enable_resampling: true
  resampler_type:  BalancedAsync
  capture_samplerate: 44100
  capture:
    type: Alsa
    channels: 2
    device: "hw:Loopback,0,0"
    format: S16LE
  playback:
    type: Alsa
    channels: 2
    device: "hw:Generic_1"
    format: S32LE

   

