[package]
name = "test73_upnp"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
eyre = "0.6"
color-eyre = "0.5"
log = "0.4"
pretty_env_logger = "0.4"
igd = "0.12"
local-ip-address = "0.4"
owo-colors = "1.3"
smallvec = "1.7"

# Для поддержки профилирования оставляем символьную информацию в релизной сборке
# [profile.release]
# debug = true