[package]
name = "test20_cpupool"
version = "0.1.0"
authors = ["DevNul <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-cpupool = "0.1.8"
futures = "0.1.29" # Нужна именно эта версия, с версиями выше не работает
