[package]
name = "feather-blocks"
version = "0.1.0"
authors = [ "caelunshun <caelunshun@gmail.com>" ]
edition = "2018"

[dependencies]
anyhow = "1"
bincode = "1"
num-traits = "0.2"
once_cell = { version = "1" }
serde = { version = "1", features = [ "derive" ] }
thiserror = "1"
vek = "0.14"
libcraft-blocks = { path = "../../libcraft/blocks" }
