[package]
name = "uploader_app"
version = "0.1.0"
authors = ["Pavel Ershov <pershov@game-insight.com>"]
edition = "2018"

[features]
default = []
flame_it = ["flame", "flamer"]

[dependencies]
tokio = {version="0.2.24", features=["full"]} # TODO: Убрать часть фичей https://docs.rs/crate/tokio/0.3.6/features
reqwest = {version="0.10.10"}
lazy_static = "1.4.0"
futures = "0.3.8"
serde_json = "1.0.60"
log = "0.4.11"
env_logger = "0.8.2"
clap = "2.33.3"
async-trait = "0.1.42"
dirs = "3.0.1"
# slack_client_lib = {git="https://github.com/DevNulPavel/slack_client_lib.git", rev="a76bfb33a2719a511c305b275d191bc5571bd65f"}
# app_center_client = {git="https://github.com/DevNulPavel/app_center_client.git", rev="b73b30b7f82f33ad0f1949ee1bfe05ac1af00bc7"}
slack_client_lib = {path="../../slack_client_lib"}
app_center_client = {path="../../app_center_client"}
any_field_is_some = {path="libs/any_field_is_some"}
flame = {version="0.2.2", optional=true}
flamer = {version="0.4.0", optional=true}

[dev-dependencies]
rand = "0.8.0"