blank_issues_enabled: false
contact_links:
  - name: VpnCloud Documentation
    url: https://vpncloud.ddswd.de/docs
    about: Please check the documentation before asking how things work.
  - name: Discussion Group on GitHub
    url: https://github.com/dswd/vpncloud/discussions
    about: Please discuss or ask anything there that is not an issue.
