[package]
name = "futex_example"
description = ""
authors = []
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"

###########################################################################

[dependencies]
parking_lot_core = { version = "^0.9.11", default-features = false, features = [
] }
# parking_lot = { version = "^0.12.4", default-features = false, features = [] }
