[package]
name = "compat"
version = "0.1.0"
authors = ["Sebastian Waisbrot <seppo0010@gmail.com>"]

[target.x86_64-unknown-linux-gnu.dependencies]
libc ="0.1.8"

[target.x86_64-apple-darwin.dependencies]
libc ="0.1.8"

[dependencies]
winapi = "0.3"
