[package]
name = "test96_ffuzzy"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2021"

##############################################################################################################

[dependencies]
# Пакет хоть и называется именно так, но библиотека внутри называется `ssdeep`
ffuzzy = "^0.3.4"