# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "actors_test"
version = "0.1.0"
authors = ["DevNul <devnulpavel@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
tokio = "0.2.13"
futures = {version = "0.3.4"}

# Альтернативный вариант установки зависимостей и параметров
[dependencies.actix]
version = "0.9.0"
