[package]
name = "test90_lalrpop"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2021"

[dependencies]
lalrpop-util = {version = "0.20.0", features = ["lexer", "regex", "unicode", "std"]}

[build-dependencies]
lalrpop = {version = "0.20.0", features = ["lexer", "unicode", "pico-args"]}