[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
polynomial = "0.2.6"
tokio = {version = "1.38.0", features = ["full"]}
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
rand = "0.8.5"