[package]
name = "test61_mongodb"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
color-eyre = "0.5"
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-error = "0.2"
tokio = {version = "1.13", features = ["full"]} # "tracing" # TODO: Оставить нужное только
futures = "0.3"
# console-subscriber = "0.1" # Специальный слой для tracing для возможности отладки через tokio-console
mongodb = "2.1"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }