[package]
name = "hand-made-fiat-shamir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hand-made-math = {path = "../hand-made-math"}
num-primes = "0.3.0"
num-bigint = {version = "0.4.5", features = ["rand"]}
rand = "0.8.5"
num-traits = "0.2.19"
pkcs7 = {path = "../hand-made-digital-signature/pkcs7"}
implementation = {path = "../hand-made-digital-signature/implementation"}
hash-function-wrapper = { version = "0.1.0", path = "../hand-made-digital-signature/hash-function-wrapper" }
