[package]
name = "ADC_RMS_httpd"
version = "0.1.0"
authors = ["ptr"]
edition = "2021"
rust-version = "1.77"

[[bin]]
name = "ADC_RMS_httpd"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[features]
default = ["std", "embassy", "esp-idf-svc/native"]

pio = ["esp-idf-svc/pio"]
std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]
embassy = ["esp-idf-svc/embassy-sync", "esp-idf-svc/critical-section", "esp-idf-svc/embassy-time-driver"]

[dependencies]
log = { version = "0.4", default-features = false }
esp-idf-svc = { version = "0.49", default-features = false }
anyhow = { version = "1", features = ["std"] }
esp-idf-hal = { version = "0.44.1", features = ["std"] }
esp-idf-sys = { version = "0.35.0", features = ["std"] }
derivative = "2.2.0"
lazy_static = "1.5.0"
parking_lot = "0.12.3"
toml-cfg = "0.2.0"
embedded-svc = "0.28.0"

[build-dependencies]
embuild = "0.32.0"

[package.metadata.esp-idf-sys]
esp_idf_tools_install_dir = "global"
esp_idf_sdkconfig = "sdkconfig"
esp_idf_sdkconfig_defaults = ["sdkconfig.defaults", "sdkconfig.defaults.ble"]
# native builder only
esp_idf_version = "v5.2.2"
esp_idf_sys_root_crate = "root-esp_idf_config"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
