[package]
name = "cve_rs"
description = "Blazingly fast memory vulnerabilities, written in 100% safe Rust."
authors = ["Speykious", "BrightShard", "Creative0708"]
version = "0.6.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/Speykious/cve-rs"
categories = ["rust-patterns"]
keywords = ["cve", "security", "soundness", "safety", "segfault"]
rust-version = "1.69.0"

###########################################################################

[features]
default = ["download_more_ram", "give_up"]
download_more_ram = ["dep:ureq"]
give_up = ["dep:oorandom", "dep:cast"]

###########################################################################

[profile.dev]
debug = false

###########################################################################

# [[bench]]
# name = "transmute"
# harness = false

###########################################################################

[dependencies]
ureq = { version = "^2.9.6", default-features = false, optional = true }
oorandom = { version = "^11.1.3", optional = true }
cast = { version = "^0.3.0", optional = true }

###########################################################################

# [dev-dependencies]
# criterion = "^0.5.1"
