[package]
name = "test63_rabbitmq"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "~1", features = ["full"] }
tokio-amqp = "~1.0"
lapin = { version = "~1", features = [] }
tracing = "~0.1"
tracing-subscriber = "~0.2"
tracing-futures = "~0.2"
human-panic = "~1.0"
quick-error = "~2.0"
dotenv = "~0.15"
futures = "~0.3"
tap = "~1.0"
rand = "0.8"

[dev-dependencies]