[package]
name = "feather-worldgen"
version = "0.6.0"
authors = [ "caelunshun <caelunshun@gmail.com>" ]
edition = "2018"

[dependencies]
base = { path = "../base", package = "feather-base" }
bitvec = "0.21"
log = "0.4"
num-traits = "0.2"
once_cell = "1"
rand = "0.7"
rand_xorshift = "0.2"
simdnoise = { git = "https://github.com/jackmott/rust-simd-noise", rev = "3a4f3e6" } # needed for https://github.com/jackmott/rust-simd-noise/pull/31 and https://github.com/jackmott/rust-simd-noise/pull/36
smallvec = "1"
strum = "0.21"

[dev-dependencies]
approx = "0.3"
