[package]
name = "test65_dynamodb"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

[dependencies]
# quick-error = "2.0"
# anyhow = "1.0"
# stable-eyre = "0.2"
backtrace = "0.3"
eyre = "0.6"
color-eyre = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-error = "0.1"
human-panic = "1.0"
tokio = { version = "1.6", features = ["full"] }
dotenv = "0.15"
rusoto_core = {version = "0.46", default_features = false, features = ["rustls"] }
rusoto_dynamodb = {version = "0.46", default_features = false, features = ["rustls"] }

[dev-dependencies]