[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
hand-made-sha = {path = "../../hand-made-sha"}
rand = "0.8.5"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
