[package]
name = "libcraft-text"
version = "0.1.0"
authors = ["Gijs de Jong <berichtaangijs@gmail.com>", "caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
hematite-nbt = { git = "https://github.com/PistonDevelopers/hematite_nbt" }
nom = "5"
nom_locate = "2"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
serde_with = "1"
uuid = { version = "0.8", features = [ "serde" ] }
thiserror = "1"
