# EUI64 record successes

[[cmd]]
name = "Running with ‘eui64.example’ prints the correct EUI64 record"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} EUI64 eui64.example"
stdout = { file = "outputs/eui64.example.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ "eui64", "madns" ]


# EUI64 record successes (JSON)

[[cmd]]
name = "Running with ‘eui64.example --json’ prints the correct EUI64 record structure"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} EUI64 eui64.example --json | jq"
stdout = { file = "outputs/eui64.example.json" }
stderr = { empty = true }
status = 0
tags = [ "eui64", "madns", "json" ]


# EUI64 record invalid packets

[[cmd]]
name = "Running with ‘too-long.eui64.invalid’ displays a record length error"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} EUI64 too-long.eui64.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: record length should be 8, got 9" }
status = 1
tags = [ "eui64", "madns" ]

[[cmd]]
name = "Running with ‘too-short.eui64.invalid’ displays a record length error"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} EUI64 too-short.eui64.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: record length should be 8, got 7" }
status = 1
tags = [ "eui64", "madns" ]

[[cmd]]
name = "Running with ‘empty.eui64.invalid’ displays a record length error"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} EUI64 empty.eui64.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: record length should be 8, got 0" }
status = 1
tags = [ "eui64", "madns" ]

[[cmd]]
name = "Running with ‘incomplete.eui64.invalid’ displays a protocol error"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} EUI64 incomplete.eui64.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: insufficient data" }
status = 1
tags = [ "eui64", "madns" ]
