# MX record successes

[[cmd]]
name = "Running with ‘mx.example’ prints the correct MX record"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} MX mx.example"
stdout = { file = "outputs/mx.example.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ "mx", "madns" ]


# MX record successes (JSON)

[[cmd]]
name = "Running with ‘mx.example --json’ prints the correct MX record structure"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} MX mx.example --json | jq"
stdout = { file = "outputs/mx.example.json" }
stderr = { empty = true }
status = 0
tags = [ "mx", "madns", "json" ]


# MX record invalid packets

[[cmd]]
name = "Running with ‘empty.mx.invalid’ displays a protocol error"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} MX empty.mx.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: insufficient data" }
status = 1
tags = [ "mx", "madns" ]

[[cmd]]
name = "Running with ‘incomplete.mx.invalid’ displays a protocol error"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} MX incomplete.mx.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: insufficient data" }
status = 1
tags = [ "mx", "madns" ]
