[[cmd]]
name = "Running with ‘formerr.invalid’ displays the error code"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} A formerr.invalid"
stdout = { string = "Status: Format Error" }
stderr = { empty = true }
status = 0
tags = [ "protocol", "madns" ]

[[cmd]]
name = "Running with ‘servfail.invalid’ displays the error code"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} A servfail.invalid"
stdout = { string = "Status: Server Failure" }
stderr = { empty = true }
status = 0
tags = [ "protocol", "madns" ]

[[cmd]]
name = "Running with ‘nxdomain.invalid’ displays the error code"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} A nxdomain.invalid"
stdout = { string = "Status: NXDomain" }
stderr = { empty = true }
status = 0
tags = [ "protocol", "madns" ]

[[cmd]]
name = "Running with ‘notimp.invalid’ displays the error code"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} A notimp.invalid"
stdout = { string = "Status: Not Implemented" }
stderr = { empty = true }
status = 0
tags = [ "protocol", "madns" ]

[[cmd]]
name = "Running with ‘refused.invalid’ displays the error code"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} A refused.invalid"
stdout = { string = "Status: Query Refused" }
stderr = { empty = true }
status = 0
tags = [ "protocol", "madns" ]
