# SRV record successes

[[cmd]]
name = "Running with ‘srv.example’ prints the correct SRV record"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} SRV srv.example"
stdout = { file = "outputs/srv.example.ansitxt" }
stderr = { empty = true }
status = 0
tags = [ "soa", "madns" ]


# SRV record successes (JSON)

[[cmd]]
name = "Running with ‘srv.example --json’ prints the correct SRV record structure"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} SRV srv.example --json | jq"
stdout = { file = "outputs/srv.example.json" }
stderr = { empty = true }
status = 0
tags = [ "soa", "madns", "json" ]


# SRV record invalid packets

[[cmd]]
name = "Running with ‘empty.srv.invalid’ displays a protocol error"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} SRV empty.srv.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: insufficient data" }
status = 1
tags = [ "soa", "madns" ]

[[cmd]]
name = "Running with ‘incomplete.srv.invalid’ displays a protocol error"
shell = "dog --colour=always ${MADNS_ARGS:-@madns.binarystar.systems:5301 --tcp} SRV incomplete.srv.invalid"
stdout = { empty = true }
stderr = { string = "Error [protocol]: Malformed packet: insufficient data" }
status = 1
tags = [ "soa", "madns" ]
