[package]
name = "feather-datapacks"
version = "0.1.0"
authors = [ "caelunshun <caelunshun@gmail.com>" ]
edition = "2018"

[dependencies]
ahash = "0.4"
anyhow = "1"
log = "0.4"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
smartstring = { version = "0.2", features = [ "serde" ] }
thiserror = "1"
ureq = { version = "2", default-features = false, features = [ "tls" ] }
zip = { version = "0.5", default-features = false, features = [ "deflate", "bzip2" ] }
